import db from './dbsketch.json' assert { type: 'json' };

const diary = ["Ima essa la mude util diga fito lh",
  "Os accusavam arranjado pe apparecer",
  "Deixam um apanha ma outono",
  "Symbolica sympathia mostrando dragaovos ja consentir as cartinhas so",
  "Intimidade firmemente vae teu lei exprimindo voz vivacidade",
  "Braga vasta ou do pegou lacos",
  "Ha mysterisa da consultar desherdal te abandonar accusavam avancando",
  "Dignidade as la ve amarguras alteracao instituto",
  "Semelhavam ama precedente poe dar pensamento",
  "Hei apertando lamentava era essencial uso hia",
  "Ala accusavam desalinho tao conseguil",
  "Quem como tem mais por para boa aza leve qual",
  "Dar adeus mande obras vamos sou",
  "Dos faces teu apeou conta vosso",
  "Es olhe pe amas rico cres veja la em",
  "Sobreaviso de produzidos vivissimos la contraveio descoberto",
  "Ala conquistar impeccavel tem ora communicar dar consideral tranquillo",
  "Receio julgar um existe divida es do tu venceu versos",
  "Eu oh alta mude como reis",
  "Sigamos ao filippe saudosa um sr covilha enganar aspecto",
  "Souberam de trocaram envolvem ir ja rodeados um penetrou",
  "Se pe arte util odio cres ceia logo em se",
  "Sabe pezo se lh povo pego anda",
  "Lia vasto lar prata vou aos coada",
  "Achar cargo teras mo la sinto",
  "Os so cerrada virtude energia estalos impuros ja",
  "Pussera ha oitenta glacial quereis sr",
  "Quem tao foge data esse cuja nos bem vez",
  "Robusto vem rasgado inteiro criadas veo paz meu remanso modinha",
  "Pequenas um lethargo illusoes ou julgando",
  "Fiz corajoso cortinas fez combater fio dez",
  "Pauloeu insisto pressas regrada teu cha",
  "Solucar hao nas femures robusto secreto tratado",
  "Pe oito para pelo tudo em os ao",
  "Deixarao ar um cabellos rispidez illudido calculos dispensa",
  "Vae pau vez veremos percebe cumpriu",
  "Mortos uns parece dentro mil deixal hei perdoa",
  "Ja contas altiva educou as tinham as idonea",
  "Empregarei miseraveis satisfacao conventual tu incendiado firmemente la",
  "Fofa do onde mola um qual moem ah amas",
  "Do responder tratarmos francfort entendida na",
  "Custa oh irmao da vulto",
  "Ou sentiu sabera espero habito tornas la eu franco no",
  "Obedecerei mau alcoolicos escriptora for differente",
  "Assim impor as passa es pegou as no jesus",
  "Marfim tambem ama uma altivo guiado voltou",
  "Era instantes embutidos indagaste sem tribunaes",
  "So ha oh prova es subiu force",
  "Despezas segredos aba dir entregar escolhem incrivel",
  "Ou preciso galeria humilde carlota ao os",
  "Dias ando tao quem sim ecco tudo tolo",
  "Fiz forradas capellao arrancou respondi lua homicida",
  "Teremos sem fazerem vae occulto",
  "Me um ha presenca despreso encolheu",
  "Com elle traz cujo fez",
  "Curto nos darei bater dia paiol preso",
  "Embargada confianca possuidor viveremos bem ceo profissao exaggeras",
  "Meia ande ja va avos no se rara iria",
  "Regimen as tirando tu familia receios",
  "Uma diga cres moem nao",
  "Noventa tal indigna perfume capital for queimar veremos tao",
  "Eu affeicoes estreitou um os se notaremos commocoes",
  "Sou diz meio face olho isto",
  "Quando repara crueis voltou cha nao desejo sao accoes",
  "Dar uma serenidade morigerado mil mau intimativa excellente",
  "Dar velhote modesto valeram foi querida",
  "Tenho lavar vao sente mao bella juras",
  "Frenesi vim batente tom parecia",
  "Vez aproveite tal amo procurava decidiste chamasses bem percorrer",
  "Ja fervoroso succumbas distincta avultados tu franqueza infernaes",
  "Veu emquanto arrancou enviesou mantemos custodio pae dar vez quizeres",
  "Reclamo caveira ja sincera impedir deserta as queriam ja la",
  "No franzindo ja captivava eu continuar ja seitornou",
  "Petroleo faz caminhou dor ler confunda",
  "Ou ha supportar casamento expliquei ja dragaovos no",
  "Quizeres extremos superior vil deixamos poe",
  "Diabos os iv justas ellaem le si terror",
  "Ahi pae quizerem sei parentes caridade",
  "Chegou fingem baldas so me saibam jamais",
  "Mostrando dou meditacao tao encontres vigorosas uns attencoes distincto"]
  

for (let i = 0; i < db.length; i++) {
    let generatedNumb = Math.random()
    let tweakedNum = String(generatedNumb).slice(2, 5) + '-' + String(generatedNumb).slice(6,9)+ '-' + String(generatedNumb).slice(10,14)
    console.log(`{ "name": "${db[i]["name"]}", "phoneNumber": "${tweakedNum}", "lastConvo": ["${diary[i]}"] },`)
}

